// Generated by CoffeeScript 1.6.3
var hooks;

hooks = require('hooks');

hooks.before('Authentication > Users > Get a User', function(transaction, done) {
  transaction.request.headers['Test Header'] = '123232323';
  console.log('before');
  return done();
});

hooks.after('Authentication > Users > Get a User', function(transaction, done) {
  console.log('after');
  return done();
});
