// Generated by CoffeeScript 1.6.3
var flattenHeaders;

flattenHeaders = function(blueprintHeaders) {
  var flatHeaders, name, values;
  flatHeaders = {};
  for (name in blueprintHeaders) {
    values = blueprintHeaders[name];
    flatHeaders[name] = values['value'].toLowerCase();
  }
  return flatHeaders;
};

module.exports = flattenHeaders;
