// Generated by CoffeeScript 1.6.3
var Hooks,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Hooks = (function() {
  function Hooks() {
    this.addHook = __bind(this.addHook, this);
    this.after = __bind(this.after, this);
    this.before = __bind(this.before, this);
    this.beforeHooks = {};
    this.afterHooks = {};
    this.transactions = {};
  }

  Hooks.prototype.before = function(name, hook) {
    return this.addHook(this.beforeHooks, name, hook);
  };

  Hooks.prototype.after = function(name, hook) {
    return this.addHook(this.afterHooks, name, hook);
  };

  Hooks.prototype.addHook = function(hooks, name, hook) {
    if (hooks[name]) {
      return hooks[name].push(hook);
    } else {
      return hooks[name] = [hook];
    }
  };

  return Hooks;

})();

module.exports = new Hooks();
