// Generated by CoffeeScript 1.6.3
var inheritHeaders;

inheritHeaders = function(actualHeaders, inheritingHeaders) {
  var name, params;
  for (name in inheritingHeaders) {
    params = inheritingHeaders[name];
    if (actualHeaders[name] === void 0) {
      actualHeaders[name] = params;
    }
  }
  return actualHeaders;
};

module.exports = inheritHeaders;
