#!/bin/sh
# Usage:
# ./scripts/cov [reporter]
#
# Example:
# ./scripts/cov html-cov > cov.html

rm -rf ./src-cov

COV=./node_modules/coffee-coverage/bin/coffeecoverage
MOCHA=./node_modules/.bin/mocha

REPORTER=$1
echo "Using Mocha reporter: $REPORTER" 1>&2
$COV --exclude node_modules,.git,test --path relative . ./src-cov 1>&2
cp -r ./test ./src-cov/test
cp ./package.json ./src-cov

$MOCHA --reporter $REPORTER --recursive --timeout 120000 --compilers 'coffee:coffee-script/register' './src-cov/test/**/*-test.coffee'

rm -rf ./src-cov
