#!/bin/sh
REPO="$1"
INSTALL_COMMAND="$2"
DREDD="$(pwd)/bin/dredd"


# Create temporary directory (http://unix.stackexchange.com/a/84980/43016)
TEMP_DIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'tmp')
ORIGINAL_PATH="$PATH"

function cleanup {
  export PATH="$ORIGINAL_PATH"
  rm -rf "$TEMP_DIR"
}

trap cleanup EXIT


export PATH="$(dirname "$DREDD"):$PATH"
cd "$TEMP_DIR"
echo "Dredd binary:" $(which dredd)
echo "Temporary directory:" $(pwd)
echo ""


git clone "$REPO" .
eval $INSTALL_COMMAND
bundle install
bundle exec cucumber
