#!/bin/bash
# This script is running the 'npm test' in a 'while true' cycle and it stops
# if the test suite fails. It's for finding flaky tests.


command () {
  ./scripts/test
}


iteration="0"
while true
do
  iteration=`echo $iteration+1 | bc`
  echo "Starting iteration $iteration"
  if ! command
  then
    echo "Failed in iteration: $iteration"
    exit 1
  fi
done
