// Generated by CoffeeScript 1.6.3
var hooks;

hooks = require('hooks');

hooks.before('Planes > Planes collection > Get Planes', function(transaction, done) {
  transaction.request.headers['header'] = '123-plane';
  console.log('before');
  return done();
});
